export { CallToAction } from '@/components/molecules/CallToAction'
export { HeaderMenu } from '@/components/molecules/HeaderMenu'
export { ConsultaTab } from '@/components/molecules/ConsultaTab'
export { IdPacienteCard } from '@/components/molecules/IDPacienteCard'
export { Seo } from '@/components/molecules/Seo'
