export type { IHomePage } from '@/interfaces/Pages/HomeProps'
export type { IAgendaPage } from '@/interfaces/Pages/AgendaPage'
export type { ILoginPage } from '@/interfaces/Pages/LoginPage'
export type { IColaboradorPage } from '@/interfaces/Pages/ColaboradorPage'

export type { IUnformCtaInput } from '@/interfaces/Inputs/UnformCtaInput'
export type { IUnformTextareaInput } from '@/interfaces/Inputs/UnformTextareaInput'
export type { ISeo } from '@/interfaces/Seo'
export type { IMobileCollapseMenu } from '@/interfaces/Header/MobileCollapseMenu'
export type { ILayout } from '@/interfaces/Layout'
export type { IHeader } from '@/interfaces/Header'
export type { IHamburgerMenu } from '@/interfaces/Header/HamburgerMenu'
export type { IHeaderLogo } from '@/interfaces/Header/HeaderLogo'
export type { IHeaderMenu } from '@/interfaces/Header/HeaderMenu'
export type { IHeaderMenuItem } from '@/interfaces/Header/HeaderMenuItem'
export type { IFooter } from '@/interfaces/Footer'

export type { ICallToAction } from '@/interfaces/CallToAction'
export type { ICallToActionForm } from '@/interfaces/CallToAction/CallToActionForm'
export type { ICallToActionButton } from '@/interfaces/CallToAction/CallToActionButton'

export type { IConsultaTab } from '@/interfaces/molecules/ConsultaTab'
export type { IIDPacienteCard } from '@/interfaces/molecules/IDPacienteCard'
export type { ILoginForm } from '@/interfaces/molecules/LoginForm'
export type { ISignInHeaderButton } from '@/interfaces/molecules/SignInHeaderButton'
export type { IColaboradorAgendaCollapse } from '@/interfaces/molecules/ColaboradorAgendaCollapse'

export type { IPacientePageTabs } from '@/interfaces/organisms/PacientePageTabs'
export type { IColaboradorComponentProps } from '@/interfaces/organisms/ColaboradorComponent'
export type { IColaboradorUnidades } from '@/interfaces/organisms/ColaboradorUnidades'
