export type { IHomePage } from '@/interfaces/HomeProps'
export type { IAgendaPage } from '@/interfaces/AgendaPage'
export type { IUnformCtaInput } from '@/interfaces/UnformCtaInput'
export type { ISeo } from '@/interfaces/Seo'
export type { IMobileCollapseMenu } from '@/interfaces/MobileCollapseMenu'
export type { ILayout } from '@/interfaces/Layout'
export type { IHeader } from '@/interfaces/Header'
export type { IHamburgerMenu } from '@/interfaces/HamburgerMenu'
export type { IHeaderLogo } from '@/interfaces/HeaderLogo'
export type { IHeaderMenu } from '@/interfaces/HeaderMenu'
export type { IHeaderMenuItem } from '@/interfaces/HeaderMenuItem'
export type { IFooter } from '@/interfaces/Footer'

export type { ICallToAction } from '@/interfaces/CallToAction'
export type { ICallToActionForm } from '@/interfaces/CallToActionForm'
export type { ICallToActionButton } from '@/interfaces/CallToActionButton'
